
languages = {
    "af": {
        "en": "Afrikaans",
        "zh": "南非荷兰语",
        "ko": "아프리칸스어",
        "ja": "アフリカーンス語",
        "ru": "африкаанс",
        "native": "Afrikaans",
    },
    "ak": {
        "en": "Akan",
        "zh": "阿坎语",
        "ko": "아칸어",
        "ja": "アカン語",
        "ru": "акан",
        "native": "Akan",
    },
    "am": {
        "en": "Amharic",
        "zh": "阿姆哈拉语",
        "ko": "암하라어",
        "ja": "アムハラ語",
        "ru": "амхарский",
        "native": "አማርኛ",
    },
    "ar": {
        "en": "Arabic",
        "zh": "阿拉伯语",
        "ko": "아랍어",
        "ja": "アラビア語",
        "ru": "арабский",
        "native": "العربية",
    },
    "as": {
        "en": "Assamese",
        "zh": "阿萨姆语",
        "ko": "아사메스어",
        "ja": "アサムシー語",
        "ru": "ассамский",
        "native": "অসমীয়া",
    },
    "ay": {
        "en": "Aymara",
        "zh": "艾马拉语",
        "ko": "아이마라어",
        "ja": "アイマラ語",
        "ru": "аймара",
        "native": "Aymara",
    },
    "az": {
        "en": "Azerbaijani",
        "zh": "阿塞拜疆语",
        "ko": "아제르바이잔어",
        "ja": "アゼルバイジャン語",
        "ru": "азербайджанский",
        "native": "Azərbaycanca",
    },
    "be": {
        "en": "Belarusian",
        "zh": "白俄罗斯语",
        "ko": "벨라루스어",
        "ja": "ベラルーシア語",
        "ru": "белорусский",
        "native": "Беларуская",
    },
    "bg": {
        "en": "Bulgarian",
        "zh": "保加利亚语",
        "ko": "불가리아어",
        "ja": "ブルガリア語",
        "ru": "болгарский",
        "native": "Български",
    },
    "bho": {
        "en": "Bhojpuri",
        "zh": "博杰普尔语",
        "ko": "보지푸리어",
        "ja": "ボジプール語",
        "ru": "боджпури",
        "native": "भोजपुरी",
    },
    "bm": {
        "en": "Bambara",
        "zh": "班巴拉语",
        "ko": "반바라어",
        "ja": "バンバラ語",
        "ru": "банту",
        "native": "Bamanankan",

    },
    "bn": {
        "en": "Bengali",
        "zh": "孟加拉语",
        "ko": "뱅고어",
        "ja": "バングラ語",
        "ru": "бенгальский",
        "native": "বাংলা",
    },
    "bs": {
        "en": "Bosnian",
        "zh": "波斯尼亚语",
        "ko": "보스니아어",
        "ja": "ボスニア語",
        "ru": "боснийский",
        "native": "Bosanski",
    },
    "ca": {
        "en": "Catalan",
        "zh": "加泰罗尼亚语",
        "ko": "카탈로니아어",
        "ja": "カタルーニャ語",
        "ru": "каталанский",
        "native": "Català",
    },
    "ceb": {
        "en": "Cebuano",
        "zh": "宿务语",
        "ko": "세부아노어",
        "ja": "セブアノ語",
        "ru": "себуано",
        "native": "Cebuano",
    },
    "ckb": {
        "en": "Central Kurdish",
        "zh": "中央库尔德语",
        "ko": "중앙쿠르드어",
        "ja": "セントラルクルド語",
        "ru": "центральный курдский",
        "native": "کوردی (میانی)",
    },
    "co": {
        "en": "Corsican",
        "zh": "科西嘉语",
        "ko": "코르시카어",
        "ja": "コルシカ語",
        "ru": "корсиканский",
        "native": "Corsican",
    },
    "cs": {
        "en": "Czech",
        "zh": "捷克语",
        "ko": "체코어",
        "ja": "チェコ語",
        "ru": "чешский",
        "native": "Čeština",
    },
    "cy": {
        "en": "Welsh",  
        "zh": "威尔士语",
        "ko": "웨일스어",
        "ja": "ウェールズ語",
        "ru": "валлийский",
        "native": "Cymraeg",
    },
    "da": {
        "en": "Danish",
        "zh": "丹麦语",
        "ko": "덴마크어",
        "ja": "デンマーク語",
        "ru": "датский",
        "native": "Dansk",
    },
    "de": {
        "en": "German",
        "zh": "德语",
        "ko": "독일어",
        "ja": "ドイツ語",
        "ru": "немецкий",
        "native": "Deutsch",
    },
    "doi": {
        "en": "Dogri",
        "zh": "多格拉语",
        "ko": "도그리어",
        "ja": "ドグリ語",
        "ru": "догри",
        "native": "डोगरी",
    },
    "dv": {
        "en": "Dhivehi",
        "zh": "迪维希语",
        "ko": "디비에이어",
        "ja": "ディビェィ語",
        "ru": "дивехи",
        "native": "ދިވެހި",
    },
    "ee": {
        "en": "Ewe",
        "zh": "埃维语",
        "ko": "에이어",
        "ja": "エヴェ語",
        "ru": "эве",
        "native": "Eʋegbe",
    },
    "el": {
        "en": "Greek",
        "zh": "希腊语",
        "ko": "그리스어",
        "ja": "ギリシャ語",
        "ru": "греческий",
        "native": "Ελληνικά",
    },
    "en": {
        "en": "English",
        "zh": "英语",
        "ko": "영어",
        "ja": "英語",
        "ru": "английский",
        "native": "English",
    },
    "eo": {
        "en": "Esperanto",
        "zh": "世界语",
        "ko": "에스페란토어",
        "ja": "エスペラント語",
        "ru": "эсперанто",
        "native": "Esperanto",
    },
    "es": {
        "en": "Spanish",
        "zh": "西班牙语",
        "ko": "스페인어",
        "ja": "スペイン語",
        "ru": "испанский",
        "native": "Español",
    },
    "et": {
        "en": "Estonian",  
        "zh": "爱沙尼亚语",
        "ko": "에스토니아어",
        "ja": "エストニア語",
        "ru": "эстонский",
        "native": "Eesti",
    },
    "eu": {
        "en": "Basque",
        "zh": "巴斯克语",
        "ko": "바스크어",
        "ja": "バスク語",
        "ru": "баскский",
        "native": "Euskara",
    },
    "fa": {
        "en": "Persian",
        "zh": "波斯语",
        "ko": "페르시아어",
        "ja": "ペルシア語",
        "ru": "персидский",
        "native": "فارسی",
    },
    "fi": {
        "en": "Finnish",
        "zh": "芬兰语",
        "ko": "핀란드어",
        "ja": "フィンランド語",
        "ru": "финляндский",
        "native": "Suomen kieli",
    },
    "fr": {
        "en": "French",
        "zh": "法语",
        "ko": "프랑스어",
        "ja": "フランス語",
        "ru": "французский",
        "native": "Français",
    },
    "fy": {
        "en": "Western Frisian",
        "zh": "西弗里西亚语",
        "ko": "서부프리시아어",
        "ja": "西部フリシア語",
        "ru": "западнофризский",
        "native": "Frysk",
    },
    "ga": {
        "en": "Irish",
        "zh": "爱尔兰语",
        "ko": "아일랜드어",
        "ja": "アイルランド語",
        "ru": "ирландский",
        "native": "Gaeilge",
    },
    "gd": {
        "en": "Scottish Gaelic",
        "zh": "苏格兰盖尔语",
        "ko": "스코틀랜드 게일어",
        "ja": "スコットランド・ゲール語",
        "ru": "шотландский гэльский",
        "native": "Gàidhlig",
    },
    "gl": {
        "en": "Galician",
        "zh": "加利西亚语",
        "ko": "가리시아어",
        "ja": "ガリシア語",
        "ru": "галисийский",
        "native": "Galego",
    },
    "gn": {
        "en": "Guarani",
        "zh": "瓜拉尼语",
        "ko": "구라니어",
        "ja": "グラニ語",
        "ru": "гварани",
        "native": "Avañe'ẽ",
    },
    "gom": {
        "en": "Konkani",
        "zh": "孔卡尼语",
        "ko": "콩카니어",
        "ja": "コンカニ語",
        "ru": "конканский",
        "native": "कोंकानी",
    },
    "gu": {
        "en": "Gujarati",
        "zh": "古吉拉特语",
        "ko": "구자라티어",
        "ja": "グジャラート語",
        "ru": "гуджарати",
        "native": "ગુજરાતી",
    },
    "ha": {
        "en": "Hausa",
        "zh": "豪萨语",
        "ko": "하우사어",
        "ja": "ハウサ語",
        "ru": "хауса",
        "native": "هَوُسَ",
    },
    "haw": {
        "en": "Hawaiian",
        "zh": "夏威夷语",
        "ko": "하와이어",
        "ja": "ハワイ語",
        "ru": "гавайский",
        "native": "ʻŌlelo Hawaiʻi",
    },
    "hi": {
        "en": "Hindi",
        "zh": "印地语",
        "ko": "힌디어",
        "ja": "ヒンディー語",
        "ru": "хинди",
        "native": "हिन्दी",
    },
    "hmn": {
        "en": "Hmong",
        "zh": "苗族语",
        "ko": "모음어",
        "ja": "モン族語",
        "ru": "мон",
        "native": "Hmong",
    },
    "hr": {
        "en": "Croatian",
        "zh": "克罗地亚语",
        "ko": "크로아티아어",
        "ja": "クロアチア語",
        "ru": "хорватский",
        "native": "Hrvatski",
    },
    "ht": {
        "en": "Haitian Creole",
        "zh": "海地克里奥尔语",
        "ko": "아이티 크리올어",
        "ja": "ハイチ・クリオール語",
        "ru": "гаитянский креольский",
        "native": "Kreyòl Ayisyen",
    },
    "hu": {
        "en": "Hungarian",
        "zh": "匈牙利语",
        "ko": "헝가리어",
        "ja": "ハンガリー語",
        "ru": "венгерский",
        "native": "Magyar",
    },
    "hy": {
        "en": "Armenian",
        "zh": "亚美尼亚语",
        "ko": "아르메니아어",
        "ja": "アルメニア語",
        "ru": "армянский",
        "native": "Հայերեն",
    },
    "id": {
        "en": "Indonesian",
        "zh": "印尼语",
        "ko": "인도네시아어",
        "ja": "インドネシア語",
        "ru": "индонезийский",
        "native": "Bahasa Indonesia",
    },
    "ig": {
        "en": "Igbo",
        "zh": "伊博语",
        "ko": "이보어",
        "ja": "イボ語",
        "ru": "игбо",
        "native": "Igbo",
    },
    "ilo": {
        "en": "Iloko",
        "zh": "伊洛科语",
        "ko": "이로코어",
        "ja": "イロコ語",
        "ru": "илоко",
        "native": "Iloko",
    },
    "is": {
        "en": "Icelandic",
        "zh": "冰岛语",
        "ko": "아이슬란드어",
        "ja": "アイスランド語",
        "ru": "исландский",
        "native": "Íslenska",
    },
    "it": {
        "en": "Italian",
        "zh": "意大利语",
        "ko": "이탈리아어",
        "ja": "イタリア語",
        "ru": "итальянский",
        "native": "Italiano",
    },
    "iw": {
        "en": "Hebrew",
        "zh": "希伯来语",
        "ko": "히브리어",
        "ja": "ヘブライ語",
        "ru": "иврит",
        "native": "עברית",
    },
    "ja": {
        "en": "Japanese",
        "zh": "日语",
        "ko": "일본어",
        "ja": "日本語",
        "ru": "японский",
        "native": "日本語",
    },
    "jw": {
        "en": "Javanese",
        "zh": "爪哇语",
        "ko": "자바어",
        "ja": "ジャワ語",
        "ru": "яванский",
        "native": "Jawa",
    },
    "ka": {
        "en": "Georgian",
        "zh": "格鲁吉亚语",
        "ko": "조지아어",
        "ja": "ジョージア語",
        "ru": "грузинский",
        "native": "ქარხნული",
    },
    "kk": {
        "en": "Kazakh",
        "zh": "哈萨克语",
        "ko": "카자흐어",
        "ja": "カザフ語",
        "ru": "казахский",
        "native": "Қазақша",
    },
    "km": {
        "en": "Khmer",
        "zh": "高棉语",
        "ko": "크메르어",
        "ja": "クーメール語",
        "ru": "кхмерский",
        "native": "ខ្មែរ",
    },
    "kn": {
        "en": "Kannada",
        "zh": "卡纳达语",
        "ko": "칸나다어",
        "ja": "カンナダ語",
        "ru": "каннада",
        "native": "ಕನ್ನಡ",
    },
    "ko": {
        "en": "Korean", 
        "zh": "韩语",
        "ko": "한국어",
        "ja": "韓国語",
        "ru": "корейский",
        "native": "한국어",
    },
    "kri": {
        "en": "Krio",
        "zh": "克里奥尔语",
        "ko": "크리올어",
        "ja": "クリオール語",
        "ru": "крио",
        "native": "Krio",
    },
    "ku": {
        "en": "Kurdish",
        "zh": "库尔德语",
        "ko": "쿠르드어",
        "ja": "クルド語",
        "ru": "курдский",
        "native": "Kurdî",
    },
    "ky": {
        "en": "Kyrgyz",
        "zh": "吉尔吉斯语",
        "ko": "키르기스어",
        "ja": "キルギス語",
        "ru": "киргизский",
        "native": "Кыргызча",
    },
    "la": {
        "en": "Latin",
        "zh": "拉丁语",
        "ko": "라틴어",
        "ja": "ラテン語",
        "ru": "латинский",
        "native": "Latin",
    },
    "lb": {
        "en": "Luxembourgish",
        "zh": "卢森堡语",
        "ko": "룩셈부르크어",
        "ja": "ルクセンブルク語",
        "ru": "люксембургский",
        "native": "Lëtzebuergesch",
    },
    "lg": {
        "en": "Ganda",
        "zh": "冈达语",
        "ko": "간다어",
        "ja": "ガンダ語",
        "ru": "ганда",
        "native": "Luganda",
    },
    "ln": {
        "en": "Lingala",
        "zh": "林加拉语",
        "ko": "링갈라어",
        "ja": "リンガラ語",
        "ru": "лингала",
        "native": "Lingala",
    },
    "lo": {
        "en": "Lao",
        "zh": "老挝语",
        "ko": "라오어",
        "ja": "ラオ語",
        "ru": "лаосский",
        "native": "ລາວ",
    },
    "lt": {
        "en": "Lithuanian",
        "zh": "立陶宛语",
        "ko": "리투아니아어",
        "ja": "リトアニア語",
        "ru": "литовский",
        "native": "Lietuvių",
    },
    "lus": {
        "en": "Lushootseed",
        "zh": "卢斯霍特塞德语",
        "ko": "루스호트세드어",
        "ja": "ルスホットセード語",
        "ru": "лусхотсед",
        "native": "Lushootseed",
    },
    "lv": {
        "en": "Latvian",
        "zh": "拉脱维亚语",
        "ko": "라트비아어",
        "ja": "ラトビア語",
        "ru": "латышский",
        "native": "Latviešu",
    },
    "mai": {
        "en": "Maithili",
        "zh": "迈蒂利语",
        "ko": "마이틸리어",
        "ja": "マイティリー語",
        "ru": "майтхили",
        "native": "मैथिली",
    },
    "mg": {
        "en": "Malagasy",
        "zh": "马达加斯加语",
        "ko": "말라가시아어",
        "ja": "マラガシア語",
        "ru": "малагасийский",
        "native": "Malagasy",
    },
    "mi": {
        "en": "Maori",
        "zh": "毛利语",
        "ko": "모리어",
        "ja": "モリー語",
        "ru": "маори",
        "native": "Maori",
    },
    "mk": {
        "en": "Macedonian",
        "zh": "马其顿语",
        "ko": "마케도니아어",
        "ja": "マケドニア語",
        "ru": "македонский",
        "native": "Македонски",
    },
    "ml": {
        "en": "Malayalam",
        "zh": "马拉雅拉姆语",
        "ko": "말라얄람어",
        "ja": "マラヤラム語",
        "ru": "малаялам",
        "native": "മലയാലം",
    },
    "mn": {
        "en": "Mongolian",
        "zh": "蒙古语",
        "ko": "몽골어",
        "ja": "モンゴル語",
        "ru": "монгольский",
        "native": "Монгол",
    },
    "mni-Mtei": {
        "en": "Meitei",
        "zh": "梅泰语",
        "ko": "메이테이어",
        "ja": "メイティー語",
        "ru": "меитэй",
        "native": "मेईटी",
    },
    "mr": {
        "en": "Marathi",
        "zh": "马拉地语",
        "ko": "마라티어",
        "ja": "マラーティー語",
        "ru": "марाची",
        "native": "मराठी",
    },
    "ms": {
        "en": "Malay",
        "zh": "马来语", 
        "ko": "말레이어",
        "ja": "マレー語",
        "ru": "малайский",
        "native": "Malay",
    },
    "mt": {
        "en": "Maltese",
        "zh": "马耳他语",
        "ko": "말티어",
        "ja": "マルタ語",
        "ru": "мальтийский",
        "native": "Malti",
    },
    "my": {
        "en": "Burmese",
        "zh": "缅甸语",
        "ko": "미얀마어",
        "ja": "ミャンマー語",
        "ru": "бирманский",
        "native": "မြန်မာဘာသာ",
    },
    "ne": {
        "en": "Nepali",
        "zh": "尼泊尔语",
        "ko": "네パル어",
        "ja": "ネパール語",
        "ru": "непальский",
        "native": "नेपाली",
    },
    "nl": {
        "en": "Dutch",
        "zh": "荷兰语",
        "ko": "네덜란드어",
        "ja": "オランダ語",
        "ru": "голландский",
        "native": "Nederlands",
    },
    "no": {
        "en": "Norwegian",
        "zh": "挪威语",
        "ko": "노르웨이어",
        "ja": "ノルウェー語",
        "ru": "норвежский",
        "native": "Norsk",
    },
    "nso": {
        "en": "Pedi",
        "zh": "佩迪语",
        "ko": "페디어",
        "ja": "ペディー語",
        "ru": "педи",
        "native": "Pedi",
    },
    "ny": {
        "en": "Chichewa",
        "zh": "契切瓦语",
        "ko": "치체바어",
        "ja": "チェチュア語",
        "ru": "чичева",
        "native": "Chichewa",
    },
    "om": {
        "en": "Oromo",
        "zh": "奥罗莫语",
        "ko": "오로모어",
        "ja": "オロモ語",
        "ru": "оромо",
        "native": "Oromo",
    },
    "or": {
        "en": "Oriya",
        "zh": "奥里亚语",
        "ko": "오리야어",
        "ja": "オリヤ語",
        "ru": "орийский",
        "native": "ଓଡ଼ିଆ",
    },
    "pa": {
        "en": "Punjabi",
        "zh": "旁遮普语",
        "ko": "펑지아어",
        "ja": "パンジャブ語",
        "ru": "панжибский",
        "native": "ਪੰਜਾਬੀ",
    },
    "pl": {
        "en": "Polish",
        "zh": "波兰语",
        "ko": "폴란드어",
        "ja": "ポーランド語",
        "ru": "польский",
        "native": "Polski",
    },
    "ps": {
        "en": "Pashto",
        "zh": "普什图语",
        "ko": "파슈투어",
        "ja": "パシュトゥ語",
        "ru": "пашту",
        "native": "پښتو",
    },
    "pt": {
        "en": "Portuguese",
        "zh": "葡萄牙语",
        "ko": "포르투갈어",
        "ja": "ポルトガル語",
        "ru": "португальский",
        "native": "Português",
    },
    "qu": {
        "en": "Quechua",
        "zh": "克丘亚语",
        "ko": "퀴치아어",
        "ja": "ケチュア語",
        "ru": "кечуа",
        "native": "Quechua",
    },
    "ro": {
        "en": "Romanian",
        "zh": "罗马尼亚语",
        "ko": "로마니아어",
        "ja": "ローマニア語",
        "ru": "румынский",
        "native": "Română",
    },
    "ru": {
        "en": "Russian",
        "zh": "俄语",
        "ko": "러시아어",
        "ja": "ロシア語",
        "ru": "русский",
        "native": "Русский",
    },
    "rw": {
        "en": "Kinyarwanda",
        "zh": "卢旺达语",
        "ko": "키냐르완다어",
        "ja": "キニャルワンダ語",
        "ru": "киняруанда",
        "native": "Kinyarwanda",
    },
    "sa": {
        "en": "Sanskrit",
        "zh": "梵语",
        "ko": "산스크리트어",
        "ja": "サンスクリット語",
        "ru": "санскрит",
        "native": "संस्कृतम्",
    },
    "sd": {
        "en": "Sindhi",
        "zh": "信德语",
        "ko": "신드어",
        "ja": "シンディー語",
        "ru": "синдхи",
        "native": "سنڌي",
    },
    "si": {
        "en": "Sinhala",
        "zh": "僧伽罗语",
        "ko": "신가랄어",
        "ja": "シンハラ語",
        "ru": "сингальский",
        "native": "සිංහල",
    },
    "sk": {
        "en": "Slovak",
        "zh": "斯洛伐克语",
        "ko": "슬로바키아어",
        "ja": "スロバキア語",
        "ru": "словацкий",
        "native": "Slovenčina",
    },
    "sl": {
        "en": "Slovenian",
        "zh": "斯洛文尼亚语",
        "ko": "슬로베니아어",
        "ja": "スロベニア語",
        "ru": "словенский",
        "native": "Slovenščina",
    },
    "sm": {
        "en": "Samoan",
        "zh": "萨摩亚语",
        "ko": "사모아어",
        "ja": "サモア語",
        "ru": "самоанский",
        "native": "Gagana Samoa",
    },
    "sn": {
        "en": "Shona",
        "zh": "绍纳语",
        "ko": "쇼나어",
        "ja": "ショナ語",
        "ru": "шоанский",
        "native": "chiShona",
    },
    "so": {
        "en": "Somali",
        "zh": "索马里语",
        "ko": "소말리아어",
        "ja": "ソマリア語",
        "ru": "сомалийский",
        "native": "Soomaali",
    },
    "sq": {
        "en": "Albanian",
        "zh": "阿尔巴尼亚语",
        "ko": "알바니아어",
        "ja": "アルバニア語",
        "ru": "албанский",
        "native": "Shqip",
    },
    "sr": {
        "en": "Serbian",
        "zh": "塞尔维亚语",
        "ko": "세르비아어",
        "ja": "セルビア語",
        "ru": "сербский",
        "native": "Srpski",
    },
    "st": {
        "en": "Sotho",
        "zh": "索托语",
        "ko": "소토어",
        "ja": "ソト語",
        "ru": "сото",
        "native": "Sotho",
    },
    "su": {
        "en": "Sundanese",
        "zh": "巽他语",
        "ko": "순다네시아어",
        "ja": "スンダネーズ語",
        "ru": "сунджанский",
        "native": "Basa Sunda",
    },
    "sv": {
        "en": "Swedish",
        "zh": "瑞典语",
        "ko": "스웨덴어",
        "ja": "スウェーデン語",
        "ru": "шведский",
        "native": "Svenska",
    },
    "sw": {
        "en": "Swahili",
        "zh": "斯瓦希里语",
        "ko": "스와힐리어",
        "ja": "スワヒリ語",
        "ru": "суахили",
        "native": "Kiswahili",
    },
    "ta": {
        "en": "Tamil",
        "zh": "泰米尔语",
        "ko": "타밀어",
        "ja": "タミル語",
        "ru": "тамильский",
        "native": "தமிழ்",
    },
    "te": {
        "en": "Telugu",
        "zh": "泰卢固语",
        "ko": "텔루구어",
        "ja": "テルグ語",
        "ru": "телугу",
        "native": "తెలుగు",
    },
    "tg": {
        "en": "Tajik",
        "zh": "塔吉克语",
        "ko": "타지크어",
        "ja": "タジク語",
        "ru": "таджикский",
        "native": "Тоҷикӣ",
    },
    "th": {
        "en": "Thai",
        "zh": "泰语",
        "ko": "태어",
        "ja": "タイ語",
        "ru": "тайский",
        "native": "ไทย",
    },
    "ti": {
        "en": "Tigrinya",
        "zh": "提格利尼亚语",
        "ko": "티그리니아어",
        "ja": "ティグリニア語",
        "ru": "тигринья",
        "native": "ትግርኛ",
    },
    "tk": {
        "en": "Turkmen",
        "zh": "土库曼语",
        "ko": "투르크만어",
        "ja": "トルクメン語",
        "ru": "туркменский",
        "native": "Türkmen",
    },
    "tl": {
        "en": "Tagalog",
        "zh": "塔加路语",
        "ko": "타갈로그어",
        "ja": "タガログ語",
        "ru": "тагальский",
        "native": "Tagalog",
    },
    "tr": {
        "en": "Turkish",
        "zh": "土耳其语",
        "ko": "터키어",
        "ja": "トルコ語",
        "ru": "турецкий",
        "native": "Türkçe",
    },
    "ts": {
        "en": "Tsonga",
        "zh": "宗加语",
        "ko": "총가어",
        "ja": "ツォンガ語",
        "ru": "цонга",
        "native": "Xitsonga",
    },
    "tt": {
        "en": "Tatar",
        "zh": "鞑靼语", 
        "ko": "타타르어",
        "ja": "タタール語",
        "ru": "татарский",
        "native": "татарский",
    },
    "ug": {
        "en": "Uighur",
        "zh": "维吾尔语",
        "ko": "위우르어",
        "ja": "ウイグル語",
        "ru": "уйгурский",
        "native": "ئۇيغۇرچە",
    },
    "uk": {
        "en": "Ukrainian",
        "zh": "乌克兰语",
        "ko": "우크라이나어",
        "ja": "ウクライナ語",
        "ru": "украинский",
        "native": "Українська",
    },
    "ur": {
        "en": "Urdu",
        "zh": "乌尔都语",
        "ko": "우르도어",
        "ja": "ウルドゥー語",
        "ru": "урду",
        "native": "اردو",
    },
    "uz": {
        "en": "Uzbek",
        "zh": "乌兹别克语",
        "ko": "우즈베크어",
        "ja": "ウズベク語",
        "ru": "узбекский",
        "native": "Oʻzbekcha",
    },
    "vi": {
        "en": "Vietnamese",
        "zh": "越南语",
        "ko": "베트남어",
        "ja": "ベトナム語",
        "ru": "вьетнамский",
        "native": "Tiếng Việt",
    },
    "xh": {
        "en": "Xhosa",
        "zh": "科萨语",
        "ko": "크사어",
        "ja": "コサ語",
        "ru": "хоса",
        "native": "Xitsonga",
    },
    "yi": {
        "en": "Yiddish",
        "zh": "意第绪语",
        "ko": "이디시어",
        "ja": "イディッシュ語",
        "ru": "идиш",
        "native": "יידיש",
    },
    "yo": {
        "en": "Yoruba",
        "zh": "约鲁巴语",
        "ko": "요루바어",
        "ja": "ヨルバ語",
        "ru": "йоруба",
        "native": "Yoruba",
    },
    "zh": {
        "googleKey": "zh-CN",
        "en": "Chinese (Simplified)",
        "zh": "简体中文",
        "ko": "중국어 (간체)",
        "ja": "中国語 (簡体)",
        "ru": "китайский (упрощенный)",
        "native": "简体中文",
    },
    "zt": {
        "googleKey": "zh-TW",
        "en": "Chinese (Traditional)",
        "zh": "繁体中文",
        "ko": "중국어 (번체)",
        "ja": "中国語 (繁體)",
        "ru": "китайский (традиционный)",
        "native": "繁体中文",
    },  
    "zu": {
        "en": "Zulu",
        "zh": "祖鲁语",
        "ko": "줄루어",
        "ja": "ズルー語",
        "ru": "зулу",
        "native": "isiZulu",
    }
}
